name: ling-env
channels: [conda-forge]
dependencies:
  - python=3.11
  - numpy=2.3.3
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - matplotlib=3.9
  - seaborn=0.13
  - nltk=3.9.2
  - spacy=3.8.7
  - spacy-lookups-data=1
  - wordcloud=1.9.4
  - regex=2024.11.6
  - tqdm=4.66
  - jupyterlab=4.2
  - ipykernel=6.29